// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('jei.hide.items', event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
	event.hide('farmingforblockheads:feeding_trough')
	event.hide('cutecore:magic_mirror_resippy')
	event.hide('modernlife:cctv_camera')
	event.hide('modernlife:cctv_screen')
	event.hide('modernlife:mirror')
	event.hide('modernlife:tall_mirror')
	event.hide('modernlife:large_mirror')
	event.hide('modernlife:massive_mirror')
	event.hide('modernlife:road_marker_white')
	event.hide('modernlife:road_marker_white_incline')
	event.hide('modernlife:road_marker_yellow')
	event.hide('modernlife:road_marker_yellow_incline')
	event.hide('modernlife:road_marker_double_yellow')
	event.hide('modernlife:road_marker_double_yellow_incline')
	event.hide('modernlife:road_marker_white_shoulder_left')
	event.hide('modernlife:road_marker_white_shoulder_left_incline')
	event.hide('modernlife:road_marker_white_shoulder_right')
	event.hide('modernlife:road_marker_white_shoulder_right_incline')
	event.hide('modernlife:paved_road')
	event.hide('modernlife:inset_light')
	event.hide('modernlife:camera')
	event.hide('modernlife:chainsaw')
	event.hide('modernlife:handgun')
	event.hide('modernlife:bullet')
	event.hide('modernlife:bullet_strip')
	event.hide('modernlife:gun_magazine')
	event.hide('modernlife:extended_gun_magazine')
	event.hide('modernlife:bicycle_item')
	event.hide('modernlife:road_marker')
	event.hide('modernlife:flashlight')
	event.hide('modernlife:tire')
	event.hide('modernlife:power_receiver')
	event.hide('modernlife:power_transmitter')
})